version: '3'

volumes:
   geoserver-data:
   settings:

services:

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      build:
        context: .
        args:
          IMAGE_VERSION: ${IMAGE_VERSION}
          JAVA_HOME: ${JAVA_HOME}
          GS_VERSION: ${GS_VERSION}
          WAR_URL: ${WAR_URL}
          DOWNLOAD_ALL_STABLE_EXTENSIONS: ${DOWNLOAD_ALL_STABLE_EXTENSIONS}
          DOWNLOAD_ALL_COMMUNITY_EXTENSIONS: ${DOWNLOAD_ALL_COMMUNITY_EXTENSIONS}
          STABLE_PLUGIN_BASE_URL: ${STABLE_PLUGIN_BASE_URL}
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - settings:/settings
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - RECREATE_DATADIR=${RECREATE_DATADIR}
        - HTTP_PROXY_NAME
        - HTTP_PROXY_PORT
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}


