
volumes:
  geoserver-data-dir:


services:
  geoserver:
    image: 'kartoza/geoserver:${TAG:-manual-build}'
    restart: 'always'
    volumes:
      - geoserver-data-dir:/opt/geoserver/data_dir
      - ./tests:/tests
    ports:
      - "8080:8080"
    environment:
      GEOSERVER_ADMIN_PASSWORD: myawesomegeoserver
      GEOSERVER_ADMIN_USER: admin
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
      GEOSERVER_CONTEXT_ROOT: foobar
      CONSOLE_HANDLER_LEVEL: WARNING
      TEST_CLASS: test_context.TestGeoServerREST
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/foobar/rest/about/version.xml"]
      interval: 1m30s
      timeout: 10s
      retries: 3



